library(stringr)
library(sva)
library(data.table)
library(readxl)
library(DESeq2)
library(DESeq)
library(pamr)
library(ggpubr)
library(Seurat)
library(cowplot)
library(scater)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(ggplot2)
library(gplots)
library(pca3d)
library(rgl)
library(scatterplot3d)
library(FactoMineR)
library(ggfortify)
library(useful)
library(tidyverse)
library(kableExtra)
library(xfun)
library(psych)
library(limma)
library(calibrate)
library(pheatmap)
library(data.table)
setwd("~/tcga/ucec")
t1 <- fread("tmp03", data.table=FALSE)
a1<-t1[1:1]
a2<-t1[2:278]
a3<-t1[279:381]
a4<-cbind(a1,a3,a2)
write.csv(a4,"a4.csv",row.names = FALSE)

#deg early_vs_late
setwd("~/tcga/ucec")
a5<-read.table("a4.csv",header=TRUE,sep=",",row.names=1)
cts_round<-round(a5)
countData<-cts_round
condition <- factor(c(rep("late",103),rep("early",277)), levels = c("late","early"))
coldata<-data.frame(row.names=colnames(countData),condition)
condition
coldata
dds<-DESeqDataSetFromMatrix(countData=countData, colData=coldata, design=~condition)
head(dds)
featureData <- data.frame(gene=rownames(a5))
mcols(dds) <- DataFrame(mcols(dds), featureData)
mcols(dds)
keep <- rowSums(counts(dds)) >= 10#keep sum counts >=10
dds <- dds[keep,]
dim(dds)
dds$condition <- factor(dds$condition, levels = c("late","early"))
dds$condition <- relevel(dds$condition, ref = "early")
dds$condition <- droplevels(dds$condition)
dds <- estimateSizeFactors(dds)
dds_norm<-counts(dds,normalized=TRUE)
head(dds_norm)
write.csv(dds_norm,"late_vs_early_norm.csv")
dds2<-DESeq(dds,fitType = "local")
resultsNames(dds2)
res <- results(dds2)
res <- results(dds2, contrast=c("condition","late","early"))
resultsNames(dds2)
write.csv(res,"late_vs_early_local.csv")

setwd("~/tcga/ucec")
res <- read.csv("late_vs_early_local.csv", header=TRUE)
head(res)
with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-1.5,2)))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
with(subset(res, pvalue<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
with(subset(res, abs(log2FoldChange)>0.3), points(log2FoldChange, -log10(pvalue), pch=20, col="orange"))
with(subset(res, pvalue<.05 & abs(log2FoldChange)>0.3), points(log2FoldChange, -log10(pvalue), pch=20, col="green"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=0.3,lty=3)
abline(v=-0.3,lty=3)